package analyzer

import (
	"context"
	"io"
	"path/filepath"

	libanalyzer "github.com/perf-analysis/perflib/analyzer"
	"github.com/perf-analysis/pkg/model"
)

// JavaCPUAnalyzer analyzes Java async-profiler CPU data.
// It delegates to the perflib engine and adapts the business model.
type JavaCPUAnalyzer struct {
	engine *libanalyzer.JavaCPUAnalyzer
	config *BaseAnalyzerConfig
}

// NewJavaCPUAnalyzer creates a new Java CPU analyzer.
func NewJavaCPUAnalyzer(config *BaseAnalyzerConfig) *JavaCPUAnalyzer {
	if config == nil {
		config = DefaultBaseAnalyzerConfig()
	}
	if config.AnalysisProfile == "" {
		config.AnalysisProfile = ProfileStandard
	}

	return &JavaCPUAnalyzer{
		engine: libanalyzer.NewJavaCPUAnalyzer(convertConfig(config)),
		config: config,
	}
}

// Name returns the analyzer name.
func (a *JavaCPUAnalyzer) Name() string {
	return a.engine.Name()
}

// Analyze performs Java CPU profiling analysis using an input file.
func (a *JavaCPUAnalyzer) Analyze(ctx context.Context, req *model.AnalysisRequest) (*model.AnalysisResponse, error) {
	libResp, err := a.engine.Analyze(ctx, convertRequest(req))
	if err != nil {
		return nil, err
	}
	return convertResponse(libResp, req.TaskUUID), nil
}

// AnalyzeFromReader performs Java CPU profiling analysis from a reader.
func (a *JavaCPUAnalyzer) AnalyzeFromReader(ctx context.Context, req *model.AnalysisRequest, dataReader io.Reader) (*model.AnalysisResponse, error) {
	libResp, err := a.engine.AnalyzeFromReader(ctx, convertRequest(req), dataReader)
	if err != nil {
		return nil, err
	}
	return convertResponse(libResp, req.TaskUUID), nil
}

// GetOutputFiles returns the list of output files generated by the analyzer.
// This is a business-only method that constructs COSKey from TaskUUID.
func (a *JavaCPUAnalyzer) GetOutputFiles(taskUUID, taskDir string) []model.OutputFile {
	return []model.OutputFile{
		{
			Name:        "Flame Graph",
			LocalPath:   filepath.Join(taskDir, "collapsed_data.json.gz"),
			COSKey:      taskUUID + "/collapsed_data.json.gz",
			ContentType: "application/gzip",
		},
		{
			Name:        "Call Graph",
			LocalPath:   filepath.Join(taskDir, "callgraph_data.json.gz"),
			COSKey:      taskUUID + "/callgraph_data.json.gz",
			ContentType: "application/gzip",
		},
	}
}
