package analyzer

import (
	"context"
	"io"
	"path/filepath"

	libanalyzer "github.com/junjiewwang/perf-analysis/perflib/analyzer"
	"github.com/junjiewwang/perf-analysis/perflib/output"
	"github.com/junjiewwang/perf-analysis/pkg/model"
)

// JavaMemAnalyzer analyzes Java async-profiler allocation/memory data.
// It delegates to the perflib engine and adapts the business model.
type JavaMemAnalyzer struct {
	engine *libanalyzer.JavaMemAnalyzer
	config *BaseAnalyzerConfig
}

// NewJavaMemAnalyzer creates a new Java memory analyzer.
func NewJavaMemAnalyzer(config *BaseAnalyzerConfig) *JavaMemAnalyzer {
	if config == nil {
		config = DefaultBaseAnalyzerConfig()
	}
	if config.AnalysisProfile == "" {
		config.AnalysisProfile = ProfileStandard
	}

	return &JavaMemAnalyzer{
		engine: libanalyzer.NewJavaMemAnalyzer(convertConfig(config)),
		config: config,
	}
}

// Name returns the analyzer name.
func (a *JavaMemAnalyzer) Name() string {
	return a.engine.Name()
}

// Analyze performs Java memory profiling analysis using an input file.
func (a *JavaMemAnalyzer) Analyze(ctx context.Context, req *model.AnalysisRequest) (*model.AnalysisResponse, error) {
	libResp, err := a.engine.Analyze(ctx, convertRequest(req))
	if err != nil {
		return nil, err
	}
	return convertResponse(libResp, req.TaskUUID), nil
}

// AnalyzeFromReader performs Java memory profiling analysis from a reader.
func (a *JavaMemAnalyzer) AnalyzeFromReader(ctx context.Context, req *model.AnalysisRequest, dataReader io.Reader) (*model.AnalysisResponse, error) {
	libResp, err := a.engine.AnalyzeFromReader(ctx, convertRequest(req), dataReader)
	if err != nil {
		return nil, err
	}
	return convertResponse(libResp, req.TaskUUID), nil
}

// GetOutputFiles returns the list of output files generated by the analyzer.
// This is a business-only method that constructs COSKey from TaskUUID.
func (a *JavaMemAnalyzer) GetOutputFiles(taskUUID, taskDir string) []model.OutputFile {
	return []model.OutputFile{
		{
			Name:        "Allocation Flame Graph",
			LocalPath:   filepath.Join(taskDir, output.FileAllocData),
			COSKey:      taskUUID + "/" + output.FileAllocData,
			ContentType: "application/gzip",
		},
		{
			Name:        "Allocation Call Graph",
			LocalPath:   filepath.Join(taskDir, output.FileAllocCallGraph),
			COSKey:      taskUUID + "/" + output.FileAllocCallGraph,
			ContentType: "application/gzip",
		},
	}
}
