package analyzer

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/perf-analysis/pkg/model"
)

// JavaCPUAnalyzer analyzes Java async-profiler CPU data.
type JavaCPUAnalyzer struct {
	*BaseAnalyzer
}

// NewJavaCPUAnalyzer creates a new Java CPU analyzer.
func NewJavaCPUAnalyzer(config *BaseAnalyzerConfig) *JavaCPUAnalyzer {
	return &JavaCPUAnalyzer{
		BaseAnalyzer: NewBaseAnalyzer(config),
	}
}

// Name returns the analyzer name.
func (a *JavaCPUAnalyzer) Name() string {
	return "java_cpu_analyzer"
}

// SupportedTypes returns the task types supported by this analyzer.
func (a *JavaCPUAnalyzer) SupportedTypes() []model.TaskType {
	return []model.TaskType{model.TaskTypeJava}
}

// Analyze performs Java CPU profiling analysis using an input file.
func (a *JavaCPUAnalyzer) Analyze(ctx context.Context, req *model.AnalysisRequest) (*model.AnalysisResponse, error) {
	if req.ProfilerType != model.ProfilerTypePerf {
		return nil, fmt.Errorf("java cpu analyzer only supports profiler type perf, got %v", req.ProfilerType)
	}

	file, err := os.Open(req.InputFile)
	if err != nil {
		return nil, fmt.Errorf("failed to open input file: %w", err)
	}
	defer file.Close()

	return a.AnalyzeFromReader(ctx, req, file)
}

// AnalyzeFromReader performs Java CPU profiling analysis from a reader.
func (a *JavaCPUAnalyzer) AnalyzeFromReader(ctx context.Context, req *model.AnalysisRequest, dataReader io.Reader) (*model.AnalysisResponse, error) {
	if req.ProfilerType != model.ProfilerTypePerf {
		return nil, fmt.Errorf("java cpu analyzer only supports profiler type perf, got %v", req.ProfilerType)
	}

	// Step 1: Parse the collapsed data
	parseResult, err := a.Parse(ctx, dataReader)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrParseError, err)
	}

	if parseResult.TotalSamples == 0 {
		return nil, ErrEmptyData
	}

	// Step 2: Determine output directory
	taskDir := req.OutputDir
	if taskDir == "" {
		taskDir, err = a.EnsureOutputDir(req.TaskUUID)
		if err != nil {
			return nil, fmt.Errorf("failed to create output directory: %w", err)
		}
	}

	// Step 3: Generate flame graph
	fg, err := a.GenerateFlameGraph(ctx, parseResult.Samples)
	if err != nil {
		return nil, fmt.Errorf("failed to generate flame graph: %w", err)
	}

	flameGraphFile := filepath.Join(taskDir, "collapsed_data.json.gz")
	if err := a.WriteFlameGraphGzip(fg, flameGraphFile); err != nil {
		return nil, fmt.Errorf("failed to write flame graph: %w", err)
	}

	// Step 4: Generate call graph
	cg, err := a.GenerateCallGraph(ctx, parseResult.Samples)
	if err != nil {
		return nil, fmt.Errorf("failed to generate call graph: %w", err)
	}

	callGraphFile := filepath.Join(taskDir, "collapsed_data.json")
	if err := a.WriteCallGraphJSON(cg, callGraphFile); err != nil {
		return nil, fmt.Errorf("failed to write call graph: %w", err)
	}

	// Step 5: Calculate statistics
	topFuncsResult := a.CalculateTopFuncs(parseResult.Samples)
	threadStatsResult := a.CalculateThreadStats(parseResult.Samples)

	// Step 6: Build top funcs JSON
	topFuncsMap := make(model.TopFuncsMap)
	for _, tf := range topFuncsResult.TopFuncs {
		topFuncsMap[tf.Name] = model.TopFuncValue{Self: tf.SelfPercent}
	}
	topFuncsJSON, _ := json.Marshal(topFuncsMap)

	// Step 7: Build active threads JSON
	activeThreads := make([]model.ThreadInfo, 0, len(threadStatsResult.Threads))
	for _, t := range threadStatsResult.Threads {
		activeThreads = append(activeThreads, model.ThreadInfo{
			TID:        t.TID,
			ThreadName: t.ThreadName,
			Samples:    t.Samples,
			Percentage: t.Percentage,
		})
	}
	activeThreadsJSON, _ := json.Marshal(activeThreads)

	// Step 8: Convert suggestions
	suggestions := make([]model.SuggestionItem, 0, len(parseResult.Suggestions))
	for _, sug := range parseResult.Suggestions {
		suggestions = append(suggestions, model.SuggestionItem{
			Suggestion: sug.Suggestion,
			FuncName:   sug.FuncName,
			Namespace:  sug.Namespace,
		})
	}

	// Step 9: Build response
	return &model.AnalysisResponse{
		TaskUUID:          req.TaskUUID,
		TopFuncs:          string(topFuncsJSON),
		TotalRecords:      int(parseResult.TotalSamples),
		FlameGraphFile:    flameGraphFile,
		CallGraphFile:     callGraphFile,
		ActiveThreadsJSON: string(activeThreadsJSON),
		Suggestions:       suggestions,
	}, nil
}

// GetOutputFiles returns the list of output files generated by the analyzer.
func (a *JavaCPUAnalyzer) GetOutputFiles(taskUUID, taskDir string) []OutputFile {
	return []OutputFile{
		{LocalPath: filepath.Join(taskDir, "collapsed_data.json.gz"), COSKey: taskUUID + "/collapsed_data.json.gz"},
		{LocalPath: filepath.Join(taskDir, "collapsed_data.json"), COSKey: taskUUID + "/collapsed_data.json"},
	}
}

// OutputFile represents a file to be uploaded.
type OutputFile struct {
	LocalPath string
	COSKey    string
}
