package analyzer

import (
	"context"
	"fmt"
	"io"
	"path/filepath"

	"github.com/perf-analysis/internal/statistics"
	"github.com/perf-analysis/pkg/model"
)

// JavaMemAnalyzer analyzes Java async-profiler allocation/memory data.
type JavaMemAnalyzer struct {
	*BaseAnalyzer
}

// NewJavaMemAnalyzer creates a new Java memory analyzer.
func NewJavaMemAnalyzer(config *BaseAnalyzerConfig) *JavaMemAnalyzer {
	return &JavaMemAnalyzer{
		BaseAnalyzer: NewBaseAnalyzer(config),
	}
}

// Name returns the analyzer name.
func (a *JavaMemAnalyzer) Name() string {
	return "java_mem_analyzer"
}

// SupportedTypes returns the task types supported by this analyzer.
func (a *JavaMemAnalyzer) SupportedTypes() []model.TaskType {
	// Java memory is TaskTypeJava with ProfilerTypeAsyncAlloc
	return []model.TaskType{model.TaskTypeJava}
}

// CanHandle checks if this analyzer can handle the given request.
func (a *JavaMemAnalyzer) CanHandle(req *model.AnalysisRequest) bool {
	return req.TaskType == model.TaskTypeJava && req.ProfilerType == model.ProfilerTypeAsyncAlloc
}

// Analyze performs Java memory profiling analysis.
func (a *JavaMemAnalyzer) Analyze(ctx context.Context, req *model.AnalysisRequest, dataReader io.Reader) (*model.AnalysisResult, error) {
	// Only handle allocation profiling (profiler type 1)
	if req.ProfilerType != model.ProfilerTypeAsyncAlloc {
		return nil, fmt.Errorf("java mem analyzer only supports profiler type async_alloc, got %v", req.ProfilerType)
	}

	// Step 1: Parse the collapsed data
	parseResult, err := a.Parse(ctx, dataReader)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrParseError, err)
	}

	if parseResult.TotalSamples == 0 {
		return nil, ErrEmptyData
	}

	// Step 2: Ensure output directory
	taskDir, err := a.EnsureOutputDir(req.TaskUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to create output directory: %w", err)
	}

	// Step 3: Generate flame graph (allocation flame graph)
	fg, err := a.GenerateFlameGraph(ctx, parseResult.Samples)
	if err != nil {
		return nil, fmt.Errorf("failed to generate flame graph: %w", err)
	}

	flameGraphFile := filepath.Join(taskDir, "alloc_data.json.gz")
	if err := a.WriteFlameGraphGzip(fg, flameGraphFile); err != nil {
		return nil, fmt.Errorf("failed to write flame graph: %w", err)
	}

	// Step 4: Generate call graph (allocation call graph)
	cg, err := a.GenerateCallGraph(ctx, parseResult.Samples)
	if err != nil {
		return nil, fmt.Errorf("failed to generate call graph: %w", err)
	}

	callGraphFile := filepath.Join(taskDir, "alloc_data.json")
	if err := a.WriteCallGraphJSON(cg, callGraphFile); err != nil {
		return nil, fmt.Errorf("failed to write call graph: %w", err)
	}

	// Step 5: Calculate statistics
	topFuncsResult := a.CalculateTopFuncs(parseResult.Samples)
	threadStatsResult := a.CalculateThreadStats(parseResult.Samples)

	// Step 6: Collect suggestions
	suggestions := parseResult.Suggestions
	if suggestions == nil {
		suggestions = make([]model.Suggestion, 0)
	}

	// Add memory-specific suggestions
	memSuggestions := a.generateMemorySuggestions(topFuncsResult)
	suggestions = append(suggestions, memSuggestions...)

	// Step 7: Build namespace result
	nsResult, err := a.BuildNamespaceResult(
		req.TaskUUID,
		parseResult,
		topFuncsResult,
		threadStatsResult,
		req.TaskUUID+"/alloc_data.json.gz",
		req.TaskUUID+"/alloc_data.json",
		suggestions,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to build namespace result: %w", err)
	}

	// Step 8: Build analysis result
	result := &model.AnalysisResult{
		TaskUUID:       req.TaskUUID,
		ContainersInfo: make(map[string]model.ContainerInfo),
		Result: map[string]model.NamespaceResult{
			"": *nsResult,
		},
		TotalRecords:            parseResult.TotalSamples,
		TotalRecordsWithSwapper: parseResult.TotalSamples,
	}

	return result, nil
}

// generateMemorySuggestions generates memory-specific suggestions.
func (a *JavaMemAnalyzer) generateMemorySuggestions(topFuncsResult *statistics.TopFuncsResult) []model.Suggestion {
	suggestions := make([]model.Suggestion, 0)

	// Check for high allocation functions
	for _, tf := range topFuncsResult.TopFuncs {
		if tf.SelfPercent > 10.0 {
			// High allocation function
			suggestions = append(suggestions, model.Suggestion{
				Type:       "memory_allocation",
				Severity:   "warning",
				Suggestion: fmt.Sprintf("函数 %s 分配内存占比 %.2f%%，建议检查是否存在频繁内存分配", tf.Name, tf.SelfPercent),
				FuncName:   tf.Name,
			})
		}
	}

	return suggestions
}

// GetOutputFiles returns the list of output files generated by the analyzer.
func (a *JavaMemAnalyzer) GetOutputFiles(taskUUID, taskDir string) []OutputFile {
	return []OutputFile{
		{LocalPath: filepath.Join(taskDir, "alloc_data.json.gz"), COSKey: taskUUID + "/alloc_data.json.gz"},
		{LocalPath: filepath.Join(taskDir, "alloc_data.json"), COSKey: taskUUID + "/alloc_data.json"},
	}
}
