package analyzer

import (
	"context"
	"io"
	"path/filepath"
	"sort"

	libanalyzer "github.com/junjiewwang/perf-analysis/perflib/analyzer"
	"github.com/junjiewwang/perf-analysis/perflib/parser/hprof"
	"github.com/junjiewwang/perf-analysis/pkg/model"
)

// JavaHeapAnalyzer analyzes Java heap dump (HPROF) files.
// It delegates to the perflib engine and adapts the business model.
type JavaHeapAnalyzer struct {
	engine *libanalyzer.JavaHeapAnalyzer
	config *BaseAnalyzerConfig
}

// JavaHeapAnalyzerOption configures the JavaHeapAnalyzer.
type JavaHeapAnalyzerOption func(*JavaHeapAnalyzer)

// NewJavaHeapAnalyzer creates a new Java heap analyzer.
func NewJavaHeapAnalyzer(config *BaseAnalyzerConfig, opts ...JavaHeapAnalyzerOption) *JavaHeapAnalyzer {
	if config == nil {
		config = DefaultBaseAnalyzerConfig()
	}

	a := &JavaHeapAnalyzer{
		config: config,
	}

	for _, opt := range opts {
		opt(a)
	}

	// Create perflib engine with converted config
	a.engine = libanalyzer.NewJavaHeapAnalyzer(convertConfig(config))

	return a
}

// Name returns the analyzer name.
func (a *JavaHeapAnalyzer) Name() string {
	return a.engine.Name()
}

// Analyze performs Java heap dump analysis using an input file.
func (a *JavaHeapAnalyzer) Analyze(ctx context.Context, req *model.AnalysisRequest) (*model.AnalysisResponse, error) {
	libResp, err := a.engine.Analyze(ctx, convertRequest(req))
	if err != nil {
		return nil, err
	}
	return convertResponse(libResp, req.TaskUUID), nil
}

// AnalyzeFromReader performs Java heap dump analysis from a reader.
func (a *JavaHeapAnalyzer) AnalyzeFromReader(ctx context.Context, req *model.AnalysisRequest, dataReader io.Reader) (*model.AnalysisResponse, error) {
	libResp, err := a.engine.AnalyzeFromReader(ctx, convertRequest(req), dataReader)
	if err != nil {
		return nil, err
	}
	return convertResponse(libResp, req.TaskUUID), nil
}

// GetOutputFiles returns the list of output files generated by the analyzer.
// This is a business-only method that constructs COSKey from TaskUUID.
func (a *JavaHeapAnalyzer) GetOutputFiles(taskUUID, taskDir string) []model.OutputFile {
	return []model.OutputFile{
		{
			Name:        "Heap Report",
			LocalPath:   filepath.Join(taskDir, "heap_analysis.json"),
			COSKey:      taskUUID + "/heap_analysis.json",
			ContentType: "application/json",
		},
		{
			Name:        "Class Histogram",
			LocalPath:   filepath.Join(taskDir, "class_histogram.json"),
			COSKey:      taskUUID + "/class_histogram.json",
			ContentType: "application/json",
		},
	}
}

// ---- Exported types for backward compatibility ----

// ClassHistogram represents a class histogram report.
type ClassHistogram struct {
	TotalClasses   int                 `json:"total_classes"`
	TotalInstances int64               `json:"total_instances"`
	TotalSize      int64               `json:"total_size"`
	Classes        []*hprof.ClassStats `json:"classes"`
}

// HeapDominatorTree represents a dominator tree for retained size analysis.
type HeapDominatorTree struct {
	Roots []*DominatorNode `json:"roots"`
}

// DominatorNode represents a node in the dominator tree.
type DominatorNode struct {
	ClassName    string           `json:"class_name"`
	ObjectID     uint64           `json:"object_id,omitempty"`
	ShallowSize  int64            `json:"shallow_size"`
	RetainedSize int64            `json:"retained_size"`
	Children     []*DominatorNode `json:"children,omitempty"`
}

// HeapAnalysisReport represents the complete heap analysis report.
type HeapAnalysisReport struct {
	Summary       *model.HeapAnalysisData `json:"summary"`
	TopClasses    []*hprof.ClassStats     `json:"top_classes"`
	Suggestions   []model.SuggestionItem  `json:"suggestions"`
	DominatorTree *HeapDominatorTree      `json:"dominator_tree,omitempty"`
}

// SortClassesBySize sorts classes by total size in descending order.
func SortClassesBySize(classes []*hprof.ClassStats) {
	sort.Slice(classes, func(i, j int) bool {
		return classes[i].TotalSize > classes[j].TotalSize
	})
}

// SortClassesByCount sorts classes by instance count in descending order.
func SortClassesByCount(classes []*hprof.ClassStats) {
	sort.Slice(classes, func(i, j int) bool {
		return classes[i].InstanceCount > classes[j].InstanceCount
	})
}
