// Package model defines output data abstractions for different analysis types.
// This is the library-clean model package without business-specific dependencies.
package model

import (
	"encoding/json"
	"sort"
)

// AnalysisDataType represents the type of analysis data.
type AnalysisDataType string

const (
	DataTypeCPUProfiling   AnalysisDataType = "cpu_profiling"
	DataTypeAllocation     AnalysisDataType = "allocation"
	DataTypeHeapDump       AnalysisDataType = "heap_dump"
	DataTypeMemoryLeak     AnalysisDataType = "memory_leak"
	DataTypeTracing        AnalysisDataType = "tracing"
	DataTypePProfCPU       AnalysisDataType = "pprof_cpu"
	DataTypePProfHeap      AnalysisDataType = "pprof_heap"
	DataTypePProfGoroutine AnalysisDataType = "pprof_goroutine"
	DataTypePProfBlock     AnalysisDataType = "pprof_block"
	DataTypePProfMutex     AnalysisDataType = "pprof_mutex"
	DataTypePProfBatch     AnalysisDataType = "pprof_batch"
)

// OutputFile describes an output file generated by analysis.
type OutputFile struct {
	Name         string `json:"name"`                    // Descriptive name (e.g., "Flame Graph", "Heap Report")
	LocalPath    string `json:"local_path"`              // Local file path
	RelativePath string `json:"relative_path,omitempty"` // Relative path within output directory
	COSKey       string `json:"cos_key,omitempty"`       // Deprecated: Object storage key, retained for backward compatibility
	ContentType  string `json:"content_type"`            // MIME type
}

// TopItem represents a generic top item (function/class/object).
type TopItem struct {
	Name       string                 `json:"name"`
	Value      int64                  `json:"value"`      // Sample count / bytes / instance count
	Percentage float64                `json:"percentage"` // Percentage of total
	Extra      map[string]interface{} `json:"extra,omitempty"`
}

// AnalysisData is the interface for all analysis data types.
// Different analysis types implement this interface to provide
// type-specific data while maintaining a common abstraction.
type AnalysisData interface {
	// Type returns the analysis data type.
	Type() AnalysisDataType

	// Summary returns a summary of the analysis as key-value pairs.
	Summary() map[string]interface{}

	// TopItems returns the top items (functions, classes, etc.) from the analysis.
	TopItems() []TopItem
}

// MarshalAnalysisData marshals AnalysisData into type-discriminated JSON.
func MarshalAnalysisData(data AnalysisData) ([]byte, error) {
	if data == nil {
		return []byte("null"), nil
	}

	wrapper := struct {
		Type string      `json:"type"`
		Data interface{} `json:"data"`
	}{
		Type: string(data.Type()),
		Data: data,
	}

	return json.Marshal(wrapper)
}

// UnmarshalAnalysisData unmarshals JSON into the appropriate AnalysisData type.
func UnmarshalAnalysisData(data []byte) (AnalysisData, error) {
	if len(data) == 0 || string(data) == "null" {
		return nil, nil
	}

	var wrapper struct {
		Type string          `json:"type"`
		Data json.RawMessage `json:"data"`
	}

	if err := json.Unmarshal(data, &wrapper); err != nil {
		return nil, err
	}

	var result AnalysisData
	switch AnalysisDataType(wrapper.Type) {
	case DataTypeCPUProfiling:
		var d CPUProfilingData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypeAllocation:
		var d AllocationData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypeHeapDump:
		var d HeapAnalysisData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypeMemoryLeak:
		var d MemoryLeakData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypeTracing:
		var d TracingData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypePProfCPU:
		var d PProfCPUData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypePProfHeap:
		var d PProfHeapData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypePProfGoroutine:
		var d PProfGoroutineData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypePProfBlock, DataTypePProfMutex:
		var d PProfBlockData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	case DataTypePProfBatch:
		var d PProfBatchData
		if err := json.Unmarshal(wrapper.Data, &d); err != nil {
			return nil, err
		}
		result = &d
	default:
		return nil, nil
	}

	return result, nil
}

// sortTopItemsByPercentage is a helper to sort TopItem slices.
func sortTopItemsByPercentage(items []TopItem) {
	sort.Slice(items, func(i, j int) bool {
		return items[i].Percentage > items[j].Percentage
	})
}
