// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: internal/parser/hprof/proto/refgraph.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GCRootTypeProto enumerates GC root types.
type GCRootTypeProto int32

const (
	GCRootTypeProto_GC_ROOT_UNKNOWN       GCRootTypeProto = 0
	GCRootTypeProto_GC_ROOT_JNI_GLOBAL    GCRootTypeProto = 1
	GCRootTypeProto_GC_ROOT_JNI_LOCAL     GCRootTypeProto = 2
	GCRootTypeProto_GC_ROOT_JAVA_FRAME    GCRootTypeProto = 3
	GCRootTypeProto_GC_ROOT_NATIVE_STACK  GCRootTypeProto = 4
	GCRootTypeProto_GC_ROOT_STICKY_CLASS  GCRootTypeProto = 5
	GCRootTypeProto_GC_ROOT_THREAD_BLOCK  GCRootTypeProto = 6
	GCRootTypeProto_GC_ROOT_MONITOR_USED  GCRootTypeProto = 7
	GCRootTypeProto_GC_ROOT_THREAD_OBJECT GCRootTypeProto = 8
)

// Enum value maps for GCRootTypeProto.
var (
	GCRootTypeProto_name = map[int32]string{
		0: "GC_ROOT_UNKNOWN",
		1: "GC_ROOT_JNI_GLOBAL",
		2: "GC_ROOT_JNI_LOCAL",
		3: "GC_ROOT_JAVA_FRAME",
		4: "GC_ROOT_NATIVE_STACK",
		5: "GC_ROOT_STICKY_CLASS",
		6: "GC_ROOT_THREAD_BLOCK",
		7: "GC_ROOT_MONITOR_USED",
		8: "GC_ROOT_THREAD_OBJECT",
	}
	GCRootTypeProto_value = map[string]int32{
		"GC_ROOT_UNKNOWN":       0,
		"GC_ROOT_JNI_GLOBAL":    1,
		"GC_ROOT_JNI_LOCAL":     2,
		"GC_ROOT_JAVA_FRAME":    3,
		"GC_ROOT_NATIVE_STACK":  4,
		"GC_ROOT_STICKY_CLASS":  5,
		"GC_ROOT_THREAD_BLOCK":  6,
		"GC_ROOT_MONITOR_USED":  7,
		"GC_ROOT_THREAD_OBJECT": 8,
	}
)

func (x GCRootTypeProto) Enum() *GCRootTypeProto {
	p := new(GCRootTypeProto)
	*p = x
	return p
}

func (x GCRootTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GCRootTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_parser_hprof_proto_refgraph_proto_enumTypes[0].Descriptor()
}

func (GCRootTypeProto) Type() protoreflect.EnumType {
	return &file_internal_parser_hprof_proto_refgraph_proto_enumTypes[0]
}

func (x GCRootTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GCRootTypeProto.Descriptor instead.
func (GCRootTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{0}
}

// ReferenceGraphProto is the serializable representation of ReferenceGraph.
// It stores the complete object reference graph for heap analysis.
type ReferenceGraphProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version for format compatibility
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Object information: objectID -> ObjectInfo
	// Using repeated instead of map for better compression
	Objects []*ObjectInfoProto `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	// Class names: classID -> className
	ClassNames []*ClassNameEntry `protobuf:"bytes,3,rep,name=class_names,json=classNames,proto3" json:"class_names,omitempty"`
	// Object references (edges in the graph)
	References []*ObjectReferenceProto `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
	// GC roots
	GcRoots []*GCRootProto `protobuf:"bytes,5,rep,name=gc_roots,json=gcRoots,proto3" json:"gc_roots,omitempty"`
	// Dominator tree data (optional, can be recomputed)
	DominatorData *DominatorDataProto `protobuf:"bytes,6,opt,name=dominator_data,json=dominatorData,proto3" json:"dominator_data,omitempty"`
	// Metadata
	Metadata      *GraphMetadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceGraphProto) Reset() {
	*x = ReferenceGraphProto{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceGraphProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceGraphProto) ProtoMessage() {}

func (x *ReferenceGraphProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceGraphProto.ProtoReflect.Descriptor instead.
func (*ReferenceGraphProto) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{0}
}

func (x *ReferenceGraphProto) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReferenceGraphProto) GetObjects() []*ObjectInfoProto {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ReferenceGraphProto) GetClassNames() []*ClassNameEntry {
	if x != nil {
		return x.ClassNames
	}
	return nil
}

func (x *ReferenceGraphProto) GetReferences() []*ObjectReferenceProto {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *ReferenceGraphProto) GetGcRoots() []*GCRootProto {
	if x != nil {
		return x.GcRoots
	}
	return nil
}

func (x *ReferenceGraphProto) GetDominatorData() *DominatorDataProto {
	if x != nil {
		return x.DominatorData
	}
	return nil
}

func (x *ReferenceGraphProto) GetMetadata() *GraphMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ObjectInfoProto stores object class and size.
type ObjectInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint64                 `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ClassId       uint64                 `protobuf:"varint,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectInfoProto) Reset() {
	*x = ObjectInfoProto{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfoProto) ProtoMessage() {}

func (x *ObjectInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfoProto.ProtoReflect.Descriptor instead.
func (*ObjectInfoProto) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectInfoProto) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *ObjectInfoProto) GetClassId() uint64 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *ObjectInfoProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ClassNameEntry maps classID to className.
type ClassNameEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       uint64                 `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassNameEntry) Reset() {
	*x = ClassNameEntry{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassNameEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassNameEntry) ProtoMessage() {}

func (x *ClassNameEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassNameEntry.ProtoReflect.Descriptor instead.
func (*ClassNameEntry) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{2}
}

func (x *ClassNameEntry) GetClassId() uint64 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *ClassNameEntry) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

// ObjectReferenceProto represents a reference from one object to another.
type ObjectReferenceProto struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FromObjectId uint64                 `protobuf:"varint,1,opt,name=from_object_id,json=fromObjectId,proto3" json:"from_object_id,omitempty"`
	ToObjectId   uint64                 `protobuf:"varint,2,opt,name=to_object_id,json=toObjectId,proto3" json:"to_object_id,omitempty"`
	FromClassId  uint64                 `protobuf:"varint,3,opt,name=from_class_id,json=fromClassId,proto3" json:"from_class_id,omitempty"`
	// Field name index (references string table for deduplication)
	FieldNameIdx  uint32 `protobuf:"varint,4,opt,name=field_name_idx,json=fieldNameIdx,proto3" json:"field_name_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectReferenceProto) Reset() {
	*x = ObjectReferenceProto{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectReferenceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReferenceProto) ProtoMessage() {}

func (x *ObjectReferenceProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReferenceProto.ProtoReflect.Descriptor instead.
func (*ObjectReferenceProto) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectReferenceProto) GetFromObjectId() uint64 {
	if x != nil {
		return x.FromObjectId
	}
	return 0
}

func (x *ObjectReferenceProto) GetToObjectId() uint64 {
	if x != nil {
		return x.ToObjectId
	}
	return 0
}

func (x *ObjectReferenceProto) GetFromClassId() uint64 {
	if x != nil {
		return x.FromClassId
	}
	return 0
}

func (x *ObjectReferenceProto) GetFieldNameIdx() uint32 {
	if x != nil {
		return x.FieldNameIdx
	}
	return 0
}

// GCRootProto represents a garbage collection root.
type GCRootProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint64                 `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Type          GCRootTypeProto        `protobuf:"varint,2,opt,name=type,proto3,enum=hprof.GCRootTypeProto" json:"type,omitempty"`
	ThreadId      uint64                 `protobuf:"varint,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	FrameIndex    int32                  `protobuf:"varint,4,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCRootProto) Reset() {
	*x = GCRootProto{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCRootProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCRootProto) ProtoMessage() {}

func (x *GCRootProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCRootProto.ProtoReflect.Descriptor instead.
func (*GCRootProto) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{4}
}

func (x *GCRootProto) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *GCRootProto) GetType() GCRootTypeProto {
	if x != nil {
		return x.Type
	}
	return GCRootTypeProto_GC_ROOT_UNKNOWN
}

func (x *GCRootProto) GetThreadId() uint64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *GCRootProto) GetFrameIndex() int32 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

// DominatorDataProto stores precomputed dominator tree data.
type DominatorDataProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether dominator tree has been computed
	Computed bool `protobuf:"varint,1,opt,name=computed,proto3" json:"computed,omitempty"`
	// Dominator relationships: objectID -> dominatorID
	Dominators []*DominatorEntry `protobuf:"bytes,2,rep,name=dominators,proto3" json:"dominators,omitempty"`
	// Retained sizes: objectID -> retainedSize
	RetainedSizes []*RetainedSizeEntry `protobuf:"bytes,3,rep,name=retained_sizes,json=retainedSizes,proto3" json:"retained_sizes,omitempty"`
	// Class retained sizes (MAT top-level view)
	ClassRetainedSizes []*ClassRetainedSizeEntry `protobuf:"bytes,4,rep,name=class_retained_sizes,json=classRetainedSizes,proto3" json:"class_retained_sizes,omitempty"`
	// Class retained sizes (attributed, non-overlapping)
	ClassRetainedSizesAttributed []*ClassRetainedSizeEntry `protobuf:"bytes,5,rep,name=class_retained_sizes_attributed,json=classRetainedSizesAttributed,proto3" json:"class_retained_sizes_attributed,omitempty"`
	// Class object IDs (Class objects are implicit GC roots)
	ClassObjectIds []uint64 `protobuf:"varint,6,rep,packed,name=class_object_ids,json=classObjectIds,proto3" json:"class_object_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DominatorDataProto) Reset() {
	*x = DominatorDataProto{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DominatorDataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DominatorDataProto) ProtoMessage() {}

func (x *DominatorDataProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DominatorDataProto.ProtoReflect.Descriptor instead.
func (*DominatorDataProto) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{5}
}

func (x *DominatorDataProto) GetComputed() bool {
	if x != nil {
		return x.Computed
	}
	return false
}

func (x *DominatorDataProto) GetDominators() []*DominatorEntry {
	if x != nil {
		return x.Dominators
	}
	return nil
}

func (x *DominatorDataProto) GetRetainedSizes() []*RetainedSizeEntry {
	if x != nil {
		return x.RetainedSizes
	}
	return nil
}

func (x *DominatorDataProto) GetClassRetainedSizes() []*ClassRetainedSizeEntry {
	if x != nil {
		return x.ClassRetainedSizes
	}
	return nil
}

func (x *DominatorDataProto) GetClassRetainedSizesAttributed() []*ClassRetainedSizeEntry {
	if x != nil {
		return x.ClassRetainedSizesAttributed
	}
	return nil
}

func (x *DominatorDataProto) GetClassObjectIds() []uint64 {
	if x != nil {
		return x.ClassObjectIds
	}
	return nil
}

// DominatorEntry maps objectID to its immediate dominator.
type DominatorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint64                 `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	DominatorId   uint64                 `protobuf:"varint,2,opt,name=dominator_id,json=dominatorId,proto3" json:"dominator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DominatorEntry) Reset() {
	*x = DominatorEntry{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DominatorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DominatorEntry) ProtoMessage() {}

func (x *DominatorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DominatorEntry.ProtoReflect.Descriptor instead.
func (*DominatorEntry) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{6}
}

func (x *DominatorEntry) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *DominatorEntry) GetDominatorId() uint64 {
	if x != nil {
		return x.DominatorId
	}
	return 0
}

// RetainedSizeEntry maps objectID to retained size.
type RetainedSizeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint64                 `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	RetainedSize  int64                  `protobuf:"varint,2,opt,name=retained_size,json=retainedSize,proto3" json:"retained_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetainedSizeEntry) Reset() {
	*x = RetainedSizeEntry{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainedSizeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainedSizeEntry) ProtoMessage() {}

func (x *RetainedSizeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainedSizeEntry.ProtoReflect.Descriptor instead.
func (*RetainedSizeEntry) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{7}
}

func (x *RetainedSizeEntry) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *RetainedSizeEntry) GetRetainedSize() int64 {
	if x != nil {
		return x.RetainedSize
	}
	return 0
}

// ClassRetainedSizeEntry maps classID to retained size.
type ClassRetainedSizeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       uint64                 `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	RetainedSize  int64                  `protobuf:"varint,2,opt,name=retained_size,json=retainedSize,proto3" json:"retained_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassRetainedSizeEntry) Reset() {
	*x = ClassRetainedSizeEntry{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassRetainedSizeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassRetainedSizeEntry) ProtoMessage() {}

func (x *ClassRetainedSizeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassRetainedSizeEntry.ProtoReflect.Descriptor instead.
func (*ClassRetainedSizeEntry) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{8}
}

func (x *ClassRetainedSizeEntry) GetClassId() uint64 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *ClassRetainedSizeEntry) GetRetainedSize() int64 {
	if x != nil {
		return x.RetainedSize
	}
	return 0
}

// GraphMetadata stores metadata about the graph.
type GraphMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of objects
	TotalObjects int64 `protobuf:"varint,1,opt,name=total_objects,json=totalObjects,proto3" json:"total_objects,omitempty"`
	// Total number of references
	TotalReferences int64 `protobuf:"varint,2,opt,name=total_references,json=totalReferences,proto3" json:"total_references,omitempty"`
	// Total number of GC roots
	TotalGcRoots int64 `protobuf:"varint,3,opt,name=total_gc_roots,json=totalGcRoots,proto3" json:"total_gc_roots,omitempty"`
	// Total heap size
	TotalHeapSize int64 `protobuf:"varint,4,opt,name=total_heap_size,json=totalHeapSize,proto3" json:"total_heap_size,omitempty"`
	// Creation timestamp (Unix milliseconds)
	CreatedAt int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Source file name (original hprof file)
	SourceFile    string `protobuf:"bytes,6,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphMetadata) Reset() {
	*x = GraphMetadata{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphMetadata) ProtoMessage() {}

func (x *GraphMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphMetadata.ProtoReflect.Descriptor instead.
func (*GraphMetadata) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{9}
}

func (x *GraphMetadata) GetTotalObjects() int64 {
	if x != nil {
		return x.TotalObjects
	}
	return 0
}

func (x *GraphMetadata) GetTotalReferences() int64 {
	if x != nil {
		return x.TotalReferences
	}
	return 0
}

func (x *GraphMetadata) GetTotalGcRoots() int64 {
	if x != nil {
		return x.TotalGcRoots
	}
	return 0
}

func (x *GraphMetadata) GetTotalHeapSize() int64 {
	if x != nil {
		return x.TotalHeapSize
	}
	return 0
}

func (x *GraphMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GraphMetadata) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

// StringTable for field name deduplication.
type StringTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTable) Reset() {
	*x = StringTable{}
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTable) ProtoMessage() {}

func (x *StringTable) ProtoReflect() protoreflect.Message {
	mi := &file_internal_parser_hprof_proto_refgraph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTable.ProtoReflect.Descriptor instead.
func (*StringTable) Descriptor() ([]byte, []int) {
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP(), []int{10}
}

func (x *StringTable) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

var File_internal_parser_hprof_proto_refgraph_proto protoreflect.FileDescriptor

const file_internal_parser_hprof_proto_refgraph_proto_rawDesc = "" +
	"\n" +
	"*internal/parser/hprof/proto/refgraph.proto\x12\x05hprof\"\xf9\x02\n" +
	"\x13ReferenceGraphProto\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x120\n" +
	"\aobjects\x18\x02 \x03(\v2\x16.hprof.ObjectInfoProtoR\aobjects\x126\n" +
	"\vclass_names\x18\x03 \x03(\v2\x15.hprof.ClassNameEntryR\n" +
	"classNames\x12;\n" +
	"\n" +
	"references\x18\x04 \x03(\v2\x1b.hprof.ObjectReferenceProtoR\n" +
	"references\x12-\n" +
	"\bgc_roots\x18\x05 \x03(\v2\x12.hprof.GCRootProtoR\agcRoots\x12@\n" +
	"\x0edominator_data\x18\x06 \x01(\v2\x19.hprof.DominatorDataProtoR\rdominatorData\x120\n" +
	"\bmetadata\x18\a \x01(\v2\x14.hprof.GraphMetadataR\bmetadata\"]\n" +
	"\x0fObjectInfoProto\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x04R\bobjectId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\x04R\aclassId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"J\n" +
	"\x0eClassNameEntry\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\x04R\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\"\xa8\x01\n" +
	"\x14ObjectReferenceProto\x12$\n" +
	"\x0efrom_object_id\x18\x01 \x01(\x04R\ffromObjectId\x12 \n" +
	"\fto_object_id\x18\x02 \x01(\x04R\n" +
	"toObjectId\x12\"\n" +
	"\rfrom_class_id\x18\x03 \x01(\x04R\vfromClassId\x12$\n" +
	"\x0efield_name_idx\x18\x04 \x01(\rR\ffieldNameIdx\"\x94\x01\n" +
	"\vGCRootProto\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x04R\bobjectId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.hprof.GCRootTypeProtoR\x04type\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\x04R\bthreadId\x12\x1f\n" +
	"\vframe_index\x18\x04 \x01(\x05R\n" +
	"frameIndex\"\x89\x03\n" +
	"\x12DominatorDataProto\x12\x1a\n" +
	"\bcomputed\x18\x01 \x01(\bR\bcomputed\x125\n" +
	"\n" +
	"dominators\x18\x02 \x03(\v2\x15.hprof.DominatorEntryR\n" +
	"dominators\x12?\n" +
	"\x0eretained_sizes\x18\x03 \x03(\v2\x18.hprof.RetainedSizeEntryR\rretainedSizes\x12O\n" +
	"\x14class_retained_sizes\x18\x04 \x03(\v2\x1d.hprof.ClassRetainedSizeEntryR\x12classRetainedSizes\x12d\n" +
	"\x1fclass_retained_sizes_attributed\x18\x05 \x03(\v2\x1d.hprof.ClassRetainedSizeEntryR\x1cclassRetainedSizesAttributed\x12(\n" +
	"\x10class_object_ids\x18\x06 \x03(\x04R\x0eclassObjectIds\"P\n" +
	"\x0eDominatorEntry\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x04R\bobjectId\x12!\n" +
	"\fdominator_id\x18\x02 \x01(\x04R\vdominatorId\"U\n" +
	"\x11RetainedSizeEntry\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x04R\bobjectId\x12#\n" +
	"\rretained_size\x18\x02 \x01(\x03R\fretainedSize\"X\n" +
	"\x16ClassRetainedSizeEntry\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\x04R\aclassId\x12#\n" +
	"\rretained_size\x18\x02 \x01(\x03R\fretainedSize\"\xed\x01\n" +
	"\rGraphMetadata\x12#\n" +
	"\rtotal_objects\x18\x01 \x01(\x03R\ftotalObjects\x12)\n" +
	"\x10total_references\x18\x02 \x01(\x03R\x0ftotalReferences\x12$\n" +
	"\x0etotal_gc_roots\x18\x03 \x01(\x03R\ftotalGcRoots\x12&\n" +
	"\x0ftotal_heap_size\x18\x04 \x01(\x03R\rtotalHeapSize\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vsource_file\x18\x06 \x01(\tR\n" +
	"sourceFile\"'\n" +
	"\vStringTable\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings*\xf0\x01\n" +
	"\x0fGCRootTypeProto\x12\x13\n" +
	"\x0fGC_ROOT_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12GC_ROOT_JNI_GLOBAL\x10\x01\x12\x15\n" +
	"\x11GC_ROOT_JNI_LOCAL\x10\x02\x12\x16\n" +
	"\x12GC_ROOT_JAVA_FRAME\x10\x03\x12\x18\n" +
	"\x14GC_ROOT_NATIVE_STACK\x10\x04\x12\x18\n" +
	"\x14GC_ROOT_STICKY_CLASS\x10\x05\x12\x18\n" +
	"\x14GC_ROOT_THREAD_BLOCK\x10\x06\x12\x18\n" +
	"\x14GC_ROOT_MONITOR_USED\x10\a\x12\x19\n" +
	"\x15GC_ROOT_THREAD_OBJECT\x10\bB6Z4github.com/perf-analysis/internal/parser/hprof/protob\x06proto3"

var (
	file_internal_parser_hprof_proto_refgraph_proto_rawDescOnce sync.Once
	file_internal_parser_hprof_proto_refgraph_proto_rawDescData []byte
)

func file_internal_parser_hprof_proto_refgraph_proto_rawDescGZIP() []byte {
	file_internal_parser_hprof_proto_refgraph_proto_rawDescOnce.Do(func() {
		file_internal_parser_hprof_proto_refgraph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_parser_hprof_proto_refgraph_proto_rawDesc), len(file_internal_parser_hprof_proto_refgraph_proto_rawDesc)))
	})
	return file_internal_parser_hprof_proto_refgraph_proto_rawDescData
}

var file_internal_parser_hprof_proto_refgraph_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_parser_hprof_proto_refgraph_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_parser_hprof_proto_refgraph_proto_goTypes = []any{
	(GCRootTypeProto)(0),           // 0: hprof.GCRootTypeProto
	(*ReferenceGraphProto)(nil),    // 1: hprof.ReferenceGraphProto
	(*ObjectInfoProto)(nil),        // 2: hprof.ObjectInfoProto
	(*ClassNameEntry)(nil),         // 3: hprof.ClassNameEntry
	(*ObjectReferenceProto)(nil),   // 4: hprof.ObjectReferenceProto
	(*GCRootProto)(nil),            // 5: hprof.GCRootProto
	(*DominatorDataProto)(nil),     // 6: hprof.DominatorDataProto
	(*DominatorEntry)(nil),         // 7: hprof.DominatorEntry
	(*RetainedSizeEntry)(nil),      // 8: hprof.RetainedSizeEntry
	(*ClassRetainedSizeEntry)(nil), // 9: hprof.ClassRetainedSizeEntry
	(*GraphMetadata)(nil),          // 10: hprof.GraphMetadata
	(*StringTable)(nil),            // 11: hprof.StringTable
}
var file_internal_parser_hprof_proto_refgraph_proto_depIdxs = []int32{
	2,  // 0: hprof.ReferenceGraphProto.objects:type_name -> hprof.ObjectInfoProto
	3,  // 1: hprof.ReferenceGraphProto.class_names:type_name -> hprof.ClassNameEntry
	4,  // 2: hprof.ReferenceGraphProto.references:type_name -> hprof.ObjectReferenceProto
	5,  // 3: hprof.ReferenceGraphProto.gc_roots:type_name -> hprof.GCRootProto
	6,  // 4: hprof.ReferenceGraphProto.dominator_data:type_name -> hprof.DominatorDataProto
	10, // 5: hprof.ReferenceGraphProto.metadata:type_name -> hprof.GraphMetadata
	0,  // 6: hprof.GCRootProto.type:type_name -> hprof.GCRootTypeProto
	7,  // 7: hprof.DominatorDataProto.dominators:type_name -> hprof.DominatorEntry
	8,  // 8: hprof.DominatorDataProto.retained_sizes:type_name -> hprof.RetainedSizeEntry
	9,  // 9: hprof.DominatorDataProto.class_retained_sizes:type_name -> hprof.ClassRetainedSizeEntry
	9,  // 10: hprof.DominatorDataProto.class_retained_sizes_attributed:type_name -> hprof.ClassRetainedSizeEntry
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_parser_hprof_proto_refgraph_proto_init() }
func file_internal_parser_hprof_proto_refgraph_proto_init() {
	if File_internal_parser_hprof_proto_refgraph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_parser_hprof_proto_refgraph_proto_rawDesc), len(file_internal_parser_hprof_proto_refgraph_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_parser_hprof_proto_refgraph_proto_goTypes,
		DependencyIndexes: file_internal_parser_hprof_proto_refgraph_proto_depIdxs,
		EnumInfos:         file_internal_parser_hprof_proto_refgraph_proto_enumTypes,
		MessageInfos:      file_internal_parser_hprof_proto_refgraph_proto_msgTypes,
	}.Build()
	File_internal_parser_hprof_proto_refgraph_proto = out.File
	file_internal_parser_hprof_proto_refgraph_proto_goTypes = nil
	file_internal_parser_hprof_proto_refgraph_proto_depIdxs = nil
}
